version: "3.8"
services:

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "true"
    networks:
      - net-connect

  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
      - 29092:29092
    expose:
      - 9092
    networks:
      - net-connect
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  auth-db:
    image: postgres
    networks:
      - net-connect
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=gabriela
      - POSTGRES_DB=auth
    volumes:
      - profile-db-volume:/var/lib/postgresql/data

  profile-db:
    image: postgres
    networks:
      - net-connect
    expose:
      - 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=gabriela
      - POSTGRES_DB=auth
    volumes:
      - auth-db-volume:/var/lib/postgresql/data

  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    networks:
      - net-connect
    expose:
      - 8081
    ports:
      - 8081:8081

  profile:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-connect
    depends_on:
      - profile-db
      - kafka
    expose:
      - 8082
    ports:
      - 8082:8082

networks:
  net-connect:
volumes:
  auth-db-volume:
  profile-db-volume:

